/*
 * @ledge/external-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.ledge.openapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateGoalRequest
 */
public class CreateGoalRequestTest {
    private final CreateGoalRequest model = new CreateGoalRequest();

    /**
     * Model tests for CreateGoalRequest
     */
    @Test
    public void testCreateGoalRequest() {
        // TODO: test CreateGoalRequest
    }

    /**
     * Test the property 'activity'
     */
    @Test
    public void activityTest() {
        // TODO: test activity
    }

    /**
     * Test the property 'questId'
     */
    @Test
    public void questIdTest() {
        // TODO: test questId
    }

    /**
     * Test the property 'bannerUrl'
     */
    @Test
    public void bannerUrlTest() {
        // TODO: test bannerUrl
    }

    /**
     * Test the property 'target'
     */
    @Test
    public void targetTest() {
        // TODO: test target
    }

    /**
     * Test the property 'instruction'
     */
    @Test
    public void instructionTest() {
        // TODO: test instruction
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

}
