/*
 * @ledge/external-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets QuestType
 */
@JsonAdapter(QuestType.Adapter.class)
public enum QuestType {
  
  INDIVIDUAL("INDIVIDUAL"),
  
  COMMUNITY("COMMUNITY");

  private String value;

  QuestType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static QuestType fromValue(String value) {
    for (QuestType b : QuestType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<QuestType> {
    @Override
    public void write(final JsonWriter jsonWriter, final QuestType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public QuestType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return QuestType.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    QuestType.fromValue(value);
  }
}

