name: Build and Publish Java API Client

on:
  workflow_dispatch:
    branches: [main]

  release:
    types: [published]

env:
  SOURCE_PATH: ./api
  REPO_ID: github
  REPO_URL: https://maven.pkg.github.com/ledgelabs/ledge-java-api

jobs:
  # copied build job from maven.yml
  build:
    name: Build @ledge/external-api
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ["8"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: "temurin"
          cache: maven
      - name: Build with Maven
        run: |
          cd ${{ env.SOURCE_PATH }}
          mvn -B package --no-transfer-progress --file pom.xml

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "temurin"
          server-id: ${{env.REPO_ID}} # Must match the server id in settings.xml

      # Authentication credentials needed to upload package
      - name: Create settings.xml
        run: |
          cd ${{ env.SOURCE_PATH }}
          echo "<settings><servers><server><id>${{env.REPO_ID}}</id><username>$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $1}')</username><password>${{ secrets.PUBLISH_PACKAGE_TOKEN }}</password></server></servers></settings>" > ${{ github.workspace }}/settings.xml

      - name: Publish package
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_PACKAGE_TOKEN }}
        run: |
          cd ${{ env.SOURCE_PATH }}
          REPO=${{ env.REPO_ID }}::default::${{ env.REPO_URL }}
          mvn -s ${{ github.workspace }}/settings.xml -U -B clean deploy -DaltDeploymentRepository="${REPO}"
