name: Build and Publish Java API Client
#trigger workflow
on:
  pull_request:

  workflow_dispatch:
    branches: [main]
  # release:
  #   types: [created]

env:
  REPO_ID: github
  REPO_URL: https://maven.pkg.github.com/ledgelabs/ledge-java-api

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "temurin"

      - name: Publish package
        env:
          GITHUB_TOKEN: ${{ secrets.GENERATE_API_CLIENT_TOKEN }}
        run: |
          touch settings.xml
          echo "<settings><servers><server><id>${{env.REPO_ID}}</id><username>$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $1}')</username><password>\${{ secrets.GENERATE_API_CLIENT_TOKEN }}</password></server></servers></settings>" > /settings.xml
          REPO=${{ env.REPO_ID }}::default::${{ env.REPO_URL }}
          mvn -s settings.xml -U -B clean deploy -DaltDeploymentRepository="${REPO}"
